### ISSUE TITLE
help(FIXEDINT) throwing exception

### ISSUE THREAD

**Issue by sfkleach** [nneonneo/fixedint#2]
It looks like there's something not quite right with the way maxval is accessed that leads to help(x), where x is a fixedint, raising an exception.

```
steve% python3
Python 3.7.3 (default, Mar 27 2019, 09:23:39) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from fixedint import *
>>> help(FixedInt(4)(3))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/_sitebuiltins.py", line 103, in __call__
    return pydoc.help(*args, **kwds)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1893, in __call__
    self.help(request)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1952, in help
    else: doc(request, 'Help on %s:', output=self._output)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1672, in doc
    pager(render_doc(thing, title, forceload))
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1665, in render_doc
    return title % desc + '\n\n' + renderer.document(object, name)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 386, in document
    if inspect.isclass(object): return self.docclass(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 1311, in docclass
    for name, kind, cls, value in classify_class_attrs(object)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pydoc.py", line 209, in classify_class_attrs
    for (name, kind, cls, value) in inspect.classify_class_attrs(object):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/inspect.py", line 434, in classify_class_attrs
    srch_obj = getattr(srch_cls, name, None)
  File "/usr/local/lib/python3.7/site-packages/fixedint/base.py", line 19, in __get__
    prop = obj.__dict__[self.name]
KeyError: 'maxval'
```

In my copy, installed using 'pip3 install fixedint' line 19 of `base.py` relates to:

```python
class FixedMetaProperty(object):
    def __init__(self, name):
        self.name = name
    def __get__(self, obj, type=None):
        prop = obj.__dict__[self.name]    #<-- this line
        return prop.__get__(obj)
    def __set__(self, obj, value):
        raise AttributeError("property %s is read-only" % self.name)
 ```

**Comment by sfkleach** [comment]
Thanks for a quick turnaround!
