### ISSUE TITLE
set slice (x[lo:hi] = y) does not work when the source (y) is a fixedint

### ISSUE THREAD

**Issue by sfkleach** [nneonneo/fixedint#3]
It appears that assigning to a slice of a fixed-int object leads to bad behaviour. In the following example, the assignment of an 8-bit number into the bottom 8-bits of a 16-bit number causes the object to be corrupted.

```python
>>> from fixedint import FixedInt
>>> f16 = FixedInt(16, signed=False, mutable=True)
>>> f8 = FixedInt(8, signed=False, mutable=True)
>>> x = f16( 0x0FFF )
>>> y = f8( 3 )
>>> bin(x)
'0b111111111111'
>>> bin(y)
'0b11'
>>> x[0:8] = int(y)
>>> x
MutableUInt16(3843)
>>> bin(x)
'0b111100000011'
>>> x[0:8] = y
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/fixedint/base.py", line 161, in __repr__
    return '%s(%s)' % (type(self).__name__, self)
  File "/usr/local/lib/python3.7/site-packages/fixedint/base.py", line 165, in __str__
    return str(int(self))
  File "/usr/local/lib/python3.7/site-packages/fixedint/base.py", line 407, in _f
    return intfunc(self._val)
TypeError: descriptor '__int__' requires a 'int' object but received a 'MutableUInt8'
```

And in this example, we assign using a fixed-int that has been generated through a slice. This avoids the corruption but clears the bits outside the intended range.

```python
>>> from fixedint import FixedInt
>>> f95 = FixedInt(95, signed=False, mutable=True)
>>> f40 = FixedInt(40, signed=False, mutable=True)
>>> x = f95( 0x0FFFFFFFFFFFFFFF )
>>> y = f40( 0xF )[0:40]
>>> bin(x)
'0b111111111111111111111111111111111111111111111111111111111111'
>>> bin(y)
'0b1111'
>>> x[0:40] = int(y)
>>> bin(x)
'0b111111111111111111110000000000000000000000000000000000001111'
>>> x[0:40] = y
>>> bin(x)
'0b1111'
>>> 
```

I did this test on a Apple Mac running
```
steve% python3
Python 3.7.6 (default, Dec 30 2019, 19:38:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by nneonneo** [comment]
Fixed in 41048d8. Thanks for the report!
